name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e

            cd /root/Hospital_Management_System_node_frontend

            echo "Current Directory"
            pwd

            echo "Pull latest code"
            git pull origin main

            echo "Installing dependencies"
            npm install

            echo "Building Next.js"
            npm run build

            echo "Restarting PM2"
            pm2 restart hospital-frontend

            echo "Deployment Successful"
